import { useState } from "react";
import { Link, useRouterState } from "@tanstack/react-router";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, XAxis, YAxis } from "recharts";
import { BarChart3, CircleDollarSign, ClipboardList, FileText, HeartHandshake, LayoutDashboard, LogOut, Menu, MoreHorizontal, Plus, Settings, Target, Trash2, Users, CalendarDays, Check, X } from "lucide-react";
import { toast } from "sonner";
import { Brand } from "./site-shell";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Progress } from "@/components/ui/progress";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { campaigns, donations, formatInr, monthly, volunteers } from "@/lib/socialsync-data";
const nav=[[LayoutDashboard,"Dashboard","/admin"],[Target,"Campaigns","/admin/campaigns"],[CircleDollarSign,"Donations","/admin/donations"],[Users,"Volunteers","/admin/volunteers"],[CalendarDays,"Events","/admin/events"],[ClipboardList,"Programs","/admin/programs"],[FileText,"Reports","/admin/reports"],[Settings,"Settings","/admin/settings"]] as const;
export function AdminShell({children,title,description}:{children:React.ReactNode;title:string;description:string}){const [open,setOpen]=useState(false);const path=useRouterState({select:s=>s.location.pathname});return <div className="min-h-screen bg-muted/50 lg:grid lg:grid-cols-[250px_1fr]"><aside className={`${open?"fixed inset-y-0 left-0 z-50 flex":"hidden"} w-[250px] flex-col border-r bg-card p-4 lg:sticky lg:top-0 lg:flex lg:h-screen`}><div className="px-2 py-3"><Brand/></div><nav className="mt-6 grid gap-1">{nav.map(([Icon,label,to])=><Link key={to} to={to} onClick={()=>setOpen(false)} className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm font-medium ${path===to?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon className="size-4"/>{label}</Link>)}</nav><Button variant="ghost" className="mt-auto justify-start" asChild><Link to="/login"><LogOut/>Logout</Link></Button></aside><main><header className="flex items-center justify-between border-b bg-card px-5 py-4 md:px-8"><div><p className="text-xs font-bold uppercase text-primary">SocialSync Admin</p><h1 className="font-display text-2xl font-semibold">{title}</h1><p className="hidden text-sm text-muted-foreground sm:block">{description}</p></div><Button variant="outline" size="icon" className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></Button><div className="hidden size-10 place-items-center rounded-full bg-primary font-bold text-primary-foreground lg:grid">SG</div></header><div className="p-5 md:p-8">{children}</div></main>{open&&<button aria-label="Close menu" className="fixed inset-0 z-40 bg-foreground/40 lg:hidden" onClick={()=>setOpen(false)}/>}</div>}
function Kpi({label,value,Icon,trend}:{label:string;value:string;Icon:React.ComponentType<{className?:string}>;trend:string}){return <div className="rounded-lg border bg-card p-5"><div className="flex justify-between"><span className="grid size-10 place-items-center rounded-md bg-surface text-primary"><Icon className="size-5"/></span><Badge variant="secondary">{trend}</Badge></div><strong className="mt-5 block font-display text-3xl">{value}</strong><p className="mt-1 text-sm text-muted-foreground">{label}</p></div>}
export function AdminDashboard(){return <AdminShell title="Dashboard" description="A live demo overview of community operations."><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Total Donations" value="₹25,40,000" Icon={CircleDollarSign} trend="+12.5%"/><Kpi label="Active Volunteers" value="150" Icon={Users} trend="+8.2%"/><Kpi label="Active Campaigns" value="12" Icon={Target} trend="3 ending soon"/><Kpi label="Lives Impacted" value="10,000+" Icon={HeartHandshake} trend="+1,240"/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="rounded-lg border bg-card p-6"><h2 className="font-display text-xl">Monthly Donations</h2><ChartContainer config={{v:{label:"Donations",color:"var(--primary)"}}} className="mt-5 h-[300px] w-full"><AreaChart data={monthly}><CartesianGrid vertical={false}/><XAxis dataKey="m"/><YAxis/><ChartTooltip content={<ChartTooltipContent/>}/><Area dataKey="v" stroke="var(--color-v)" fill="var(--color-v)" fillOpacity={.18}/></AreaChart></ChartContainer></div><div className="rounded-lg border bg-card p-6"><h2 className="font-display text-xl">Volunteer Growth</h2><ChartContainer config={{v:{label:"Volunteers",color:"var(--warm)"}}} className="mt-5 h-[300px] w-full"><BarChart data={monthly.map((x,i)=>({...x,v:[62,78,92,109,128,150][i]}))}><CartesianGrid vertical={false}/><XAxis dataKey="m"/><YAxis/><Bar dataKey="v" fill="var(--color-v)" radius={4}/></BarChart></ChartContainer></div></div><div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-lg border bg-card p-6"><h2 className="font-display text-xl">Campaign Performance</h2><div className="mt-6 space-y-5">{campaigns.slice(0,4).map(c=><div key={c.id}><div className="mb-2 flex justify-between text-sm"><span>{c.title}</span><strong>{Math.round(c.raised/c.goal*100)}%</strong></div><Progress value={c.raised/c.goal*100}/></div>)}</div></div><div className="rounded-lg border bg-card p-6"><h2 className="font-display text-xl">Recent Activity</h2><div className="mt-4 divide-y">{[[Users,"New volunteer registered","2 minutes ago"],[CircleDollarSign,"₹5,000 donation received","18 minutes ago"],[Target,"Campaign updated","1 hour ago"],[CalendarDays,"New event created","3 hours ago"]].map(([Icon,t,d])=><div key={t as string} className="flex gap-3 py-4"><span className="grid size-9 place-items-center rounded-md bg-surface text-primary"><Icon className="size-4"/></span><div><p className="text-sm font-medium">{t as string}</p><p className="text-xs text-muted-foreground">{d as string}</p></div></div>)}</div></div></div></AdminShell>}
export function AdminCampaigns(){const [open,setOpen]=useState(false);return <AdminShell title="Campaigns" description="Create, review and manage fundraising campaigns."><div className="flex justify-end"><Button onClick={()=>setOpen(true)}><Plus/>Create New Campaign</Button></div><DataWrap><Table><TableHeader><TableRow>{["Campaign Name","Category","Goal","Raised","Progress","Status","Deadline","Actions"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{campaigns.map(c=><TableRow key={c.id}><TableCell className="font-medium">{c.title}</TableCell><TableCell>{c.category}</TableCell><TableCell>{formatInr(c.goal)}</TableCell><TableCell>{formatInr(c.raised)}</TableCell><TableCell><Progress value={c.raised/c.goal*100} className="w-24"/></TableCell><TableCell><Badge>Active</Badge></TableCell><TableCell>{c.deadline}</TableCell><TableCell><div className="flex gap-1"><Button variant="ghost" size="icon" aria-label="View" onClick={()=>toast.info(`Viewing ${c.title}`)}><MoreHorizontal/></Button><Button variant="ghost" size="icon" aria-label="Delete" onClick={()=>toast.success("Demo campaign removed from view") }><Trash2/></Button></div></TableCell></TableRow>)}</TableBody></Table></DataWrap><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Create New Campaign</DialogTitle><DialogDescription>Add a demo campaign to the management queue.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();setOpen(false);toast.success("Demo campaign created")}} className="grid gap-4"><Field label="Campaign Name"/><div><Label>Description</Label><Textarea required/></div><Field label="Category"/><Field label="Goal Amount" type="number"/><Field label="Deadline" type="date"/><Field label="Campaign Image" type="file"/><Field label="Status"/><Button>Create Campaign</Button></form></DialogContent></Dialog></AdminShell>}
function Field({label,type="text"}:{label:string;type?:string}){return <div><Label>{label}</Label><Input className="mt-2" type={type} required/></div>}
function DataWrap({children}:{children:React.ReactNode}){return <div className="mt-5 overflow-x-auto rounded-lg border bg-card">{children}</div>}
export function AdminVolunteers(){const [items,setItems]=useState(volunteers);const update=(email:string,status:string)=>{setItems(v=>v.map(x=>x.email===email?{...x,status}:x));toast.success(`Volunteer marked ${status.toLowerCase()}`)};return <AdminShell title="Volunteers" description="Review applications and coordinate your active volunteer network."><DataWrap><Table><TableHeader><TableRow>{["Name","Email","Skills","Interest Area","Status","Registration Date","Actions"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{items.map(v=><TableRow key={v.email}><TableCell className="font-medium">{v.name}</TableCell><TableCell>{v.email}</TableCell><TableCell>{v.skills}</TableCell><TableCell>{v.interest}</TableCell><TableCell><Badge variant={v.status==="Approved"?"default":"secondary"}>{v.status}</Badge></TableCell><TableCell>{v.date}</TableCell><TableCell><div className="flex gap-1"><Button size="icon" variant="ghost" aria-label="Approve" onClick={()=>update(v.email,"Approved")}><Check/></Button><Button size="icon" variant="ghost" aria-label="Reject" onClick={()=>update(v.email,"Rejected")}><X/></Button></div></TableCell></TableRow>)}</TableBody></Table></DataWrap></AdminShell>}
export function AdminDonations(){const [query,setQuery]=useState("");const rows=donations.filter(d=>d.campaign.toLowerCase().includes(query.toLowerCase())||d.donor.toLowerCase().includes(query.toLowerCase()));return <AdminShell title="Donations" description="Monitor demo contributions and payment statuses."><div className="grid gap-3 md:grid-cols-3"><Input placeholder="Filter by donor or campaign" value={query} onChange={e=>setQuery(e.target.value)}/><Input type="date"/><Input type="number" placeholder="Minimum amount"/></div><DataWrap><Table><TableHeader><TableRow>{["Donor","Campaign","Amount","Payment Method","Date","Status"].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((d,i)=><TableRow key={i}><TableCell className="font-medium">{d.donor}</TableCell><TableCell>{d.campaign}</TableCell><TableCell>{formatInr(d.amount)}</TableCell><TableCell>{d.method}</TableCell><TableCell>{d.date}</TableCell><TableCell><Badge variant={d.status==="Completed"?"default":"secondary"}>{d.status}</Badge></TableCell></TableRow>)}</TableBody></Table></DataWrap></AdminShell>}
export function AdminPlaceholder({section}:{section:string}){return <AdminShell title={section} description={`Manage ${section.toLowerCase()} for SocialSync.`}><div className="grid min-h-[420px] place-items-center rounded-lg border border-dashed bg-card p-8 text-center"><div><BarChart3 className="mx-auto size-10 text-primary"/><h2 className="mt-4 font-display text-2xl">{section} workspace</h2><p className="mx-auto mt-2 max-w-md text-muted-foreground">This portfolio view demonstrates a ready management area with clear navigation and scalable structure.</p><Button className="mt-6" onClick={()=>toast.info(`${section} demo action opened`)}>Open {section}</Button></div></div></AdminShell>}
