import { Link } from "@tanstack/react-router";
import { ArrowRight, CalendarDays, Clock3, Heart, MapPin, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { type Campaign, formatInr } from "@/lib/socialsync-data";

export function PageHero({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <section className="subtle-grid border-b bg-surface/70"><div className="section-shell py-16 md:py-24"><p className="mb-4 text-sm font-bold uppercase text-primary">{eyebrow}</p><h1 className="display-title max-w-4xl text-4xl md:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{description}</p></div></section>}
export function SectionHead({eyebrow,title,description,center=false}:{eyebrow?:string;title:string;description?:string;center?:boolean}){return <div className={`mb-10 ${center?"mx-auto max-w-2xl text-center":"max-w-2xl"}`}>{eyebrow&&<p className="mb-3 text-sm font-bold uppercase text-primary">{eyebrow}</p>}<h2 className="display-title text-3xl md:text-5xl">{title}</h2>{description&&<p className="mt-4 leading-7 text-muted-foreground">{description}</p>}</div>}
export function CampaignCard({c}:{c:Campaign}){const pct=Math.round(c.raised/c.goal*100); return <article className="card-lift overflow-hidden rounded-lg border bg-card shadow-sm"><Link to="/campaigns/$campaignId" params={{campaignId:c.id}} className="block overflow-hidden"><img src={c.image} alt={`${c.title} campaign`} width={1536} height={1024} loading="lazy" className="aspect-[16/10] w-full object-cover transition-transform duration-500 hover:scale-105"/></Link><div className="p-5"><Badge variant="secondary">{c.category}</Badge><h3 className="mt-3 font-display text-xl font-semibold"><Link to="/campaigns/$campaignId" params={{campaignId:c.id}} className="hover:text-primary">{c.title}</Link></h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{c.description}</p><div className="mt-5"><div className="mb-2 flex justify-between text-sm"><strong>{formatInr(c.raised)}</strong><span className="text-muted-foreground">{pct}%</span></div><Progress value={pct} className="h-2"/><div className="mt-2 flex justify-between text-xs text-muted-foreground"><span>Goal {formatInr(c.goal)}</span><span>{c.supporters} supporters</span></div></div><div className="mt-5 flex items-center justify-between border-t pt-4"><span className="flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="size-3.5"/>{c.deadline}</span><Button size="sm" asChild><Link to="/donate" search={{campaign:c.id}}><Heart/>Support</Link></Button></div></div></article>}
export function EventCard({event,onRegister}:{event:{title:string;date:string;location:string;needed:number;description:string;image:string};onRegister:()=>void}){return <article className="overflow-hidden rounded-lg border bg-card shadow-sm"><img src={event.image} alt={event.title} width={1536} height={1024} loading="lazy" className="aspect-[16/9] w-full object-cover"/><div className="p-5"><h3 className="font-display text-xl font-semibold">{event.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{event.description}</p><div className="mt-4 grid gap-2 text-sm"><span className="flex gap-2"><CalendarDays className="size-4 text-primary"/>{event.date}</span><span className="flex gap-2"><MapPin className="size-4 text-primary"/>{event.location}</span><span className="flex gap-2"><Users className="size-4 text-primary"/>{event.needed} volunteers needed</span></div><Button className="mt-5 w-full" onClick={onRegister}>Register for Event<ArrowRight/></Button></div></article>}
