import { Link, useRouterState } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, Facebook, HeartHandshake, Instagram, Linkedin, Menu, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

const links = [["/","Home"],["/about","About"],["/programs","Programs"],["/campaigns","Campaigns"],["/volunteers","Volunteers"],["/events","Events"],["/impact","Impact"],["/contact","Contact"]] as const;
export function Brand({ light=false }:{light?:boolean}) { return <Link to="/" className="flex items-center gap-2.5"><span className={`grid size-9 place-items-center rounded-lg ${light?"bg-background text-primary":"bg-primary text-primary-foreground"}`}><HeartHandshake className="size-5"/></span><span className={`font-display text-xl font-bold ${light?"text-primary-foreground":"text-foreground"}`}>Social<span className={light?"text-accent":"text-primary"}>Sync</span></span></Link> }
export function SiteHeader(){ const [open,setOpen]=useState(false); const path=useRouterState({select:s=>s.location.pathname}); if(path.startsWith("/admin")) return null; return <header className="sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur"><div className="section-shell flex h-18 items-center justify-between"><Brand/><nav className="hidden items-center gap-5 xl:flex">{links.map(([to,label])=><Link key={to} to={to} className={`text-sm font-medium transition-colors hover:text-primary ${path===to?"text-primary":"text-muted-foreground"}`}>{label}</Link>)}</nav><div className="hidden items-center gap-2 md:flex"><Button variant="ghost" asChild><Link to="/login">Login</Link></Button><Button variant="warm" asChild><Link to="/donate"><HeartHandshake/>Donate Now</Link></Button></div><Button aria-label="Open menu" variant="ghost" size="icon" className="xl:hidden" onClick={()=>setOpen(v=>!v)}>{open?<X/>:<Menu/>}</Button></div>{open&&<div className="border-t bg-background px-5 py-5 xl:hidden"><nav className="grid gap-1">{links.map(([to,label])=><Link key={to} to={to} onClick={()=>setOpen(false)} className="rounded-md px-3 py-3 font-medium hover:bg-muted">{label}</Link>)}<div className="mt-3 grid grid-cols-2 gap-2"><Button variant="outline" asChild><Link to="/login">Login</Link></Button><Button variant="warm" asChild><Link to="/donate">Donate Now</Link></Button></div></nav></div>}</header> }
export function SiteFooter(){ const path=useRouterState({select:s=>s.location.pathname}); if(path.startsWith("/admin")) return null; const subscribe=(e:React.FormEvent)=>{e.preventDefault();toast.success("You're on the SocialSync update list.")}; return <footer className="bg-foreground text-primary-foreground"><div className="section-shell grid gap-10 py-14 md:grid-cols-2 lg:grid-cols-5"><div className="lg:col-span-2"><Brand light/><p className="mt-5 max-w-sm text-sm leading-7 text-primary-foreground/70">Technology-powered community engagement for a better tomorrow.</p><p className="mt-3 font-display text-lg">Connect. Contribute. Create Impact.</p></div>{[["Platform",[["Campaigns","/campaigns"],["Volunteers","/volunteers"],["Events","/events"],["Impact","/impact"]]],["Organization",[["About","/about"],["Programs","/programs"],["Contact","/contact"]]]].map(([title,items])=><div key={title as string}><h3 className="mb-4 font-semibold">{title as string}</h3><ul className="space-y-3 text-sm text-primary-foreground/65">{(items as string[][]).map(([l,to])=><li key={l}><Link to={to} className="hover:text-accent">{l}</Link></li>)}</ul></div>)}<div><h3 className="font-semibold">Stay updated on our impact.</h3><form onSubmit={subscribe} className="mt-4 flex gap-2"><Input type="email" required aria-label="Newsletter email" placeholder="Email address" className="border-primary-foreground/20 bg-primary-foreground/10 text-primary-foreground placeholder:text-primary-foreground/50"/><Button aria-label="Subscribe" size="icon" variant="warm"><ArrowRight/></Button></form><div className="mt-5 flex gap-2">{[Linkedin,Instagram,Facebook].map((Icon,i)=><Button key={i} variant="ghost" size="icon" aria-label="Social link" className="text-primary-foreground hover:bg-primary-foreground/10"><Icon/></Button>)}</div></div></div><div className="border-t border-primary-foreground/10 py-5 text-center text-xs text-primary-foreground/55">© 2026 SocialSync. All Rights Reserved. · Demo platform — no real payments or personal data storage.</div></footer> }
