/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCampaignsRouteImport } from './routes/admin.campaigns'
import { Route as AdminDonationsRouteImport } from './routes/admin.donations'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminProgramsRouteImport } from './routes/admin.programs'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminVolunteersRouteImport } from './routes/admin.volunteers'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns.$campaignId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampaignsRoute = AdminCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDonationsRoute = AdminDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/$campaignId',
  path: '/$campaignId',
  getParentRoute: () => CampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/campaigns': typeof CampaignsRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/volunteers': typeof VolunteersRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/campaigns': typeof CampaignsRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/volunteers': typeof VolunteersRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/campaigns': typeof CampaignsRouteWithChildren
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/impact': typeof ImpactRoute
  '/login': typeof LoginRoute
  '/programs': typeof ProgramsRoute
  '/volunteers': typeof VolunteersRoute
  '/admin/campaigns': typeof AdminCampaignsRoute
  '/admin/donations': typeof AdminDonationsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/campaigns'
    | '/contact'
    | '/donate'
    | '/events'
    | '/impact'
    | '/login'
    | '/programs'
    | '/volunteers'
    | '/admin/campaigns'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/programs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/volunteers'
    | '/campaigns/$campaignId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/campaigns'
    | '/contact'
    | '/donate'
    | '/events'
    | '/impact'
    | '/login'
    | '/programs'
    | '/volunteers'
    | '/admin/campaigns'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/programs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/volunteers'
    | '/campaigns/$campaignId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/campaigns'
    | '/contact'
    | '/donate'
    | '/events'
    | '/impact'
    | '/login'
    | '/programs'
    | '/volunteers'
    | '/admin/campaigns'
    | '/admin/donations'
    | '/admin/events'
    | '/admin/programs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/volunteers'
    | '/campaigns/$campaignId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CampaignsRoute: typeof CampaignsRouteWithChildren
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  ImpactRoute: typeof ImpactRoute
  LoginRoute: typeof LoginRoute
  ProgramsRoute: typeof ProgramsRoute
  VolunteersRoute: typeof VolunteersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campaigns': {
      id: '/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AdminCampaignsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/donations': {
      id: '/admin/donations'
      path: '/donations'
      fullPath: '/admin/donations'
      preLoaderRoute: typeof AdminDonationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/campaigns/$campaignId': {
      id: '/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof CampaignsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCampaignsRoute: typeof AdminCampaignsRoute
  AdminDonationsRoute: typeof AdminDonationsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampaignsRoute: AdminCampaignsRoute,
  AdminDonationsRoute: AdminDonationsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CampaignsRouteChildren {
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRoute
}

const CampaignsRouteChildren: CampaignsRouteChildren = {
  CampaignsCampaignIdRoute: CampaignsCampaignIdRoute,
}

const CampaignsRouteWithChildren = CampaignsRoute._addFileChildren(
  CampaignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CampaignsRoute: CampaignsRouteWithChildren,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  ImpactRoute: ImpactRoute,
  LoginRoute: LoginRoute,
  ProgramsRoute: ProgramsRoute,
  VolunteersRoute: VolunteersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
